---
Name: template-selector
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Mouseketeers\TemplateSelector\TemplateSelector
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Mouseketeers\TemplateSelector\TemplateSelectorController